### ISSUE TITLE
Setting: Secret Shrine Requirements

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#108]
Self-explanatory. Just two options with a drop-down? Or something. I don't know.

-Vanilla (current functionality)
-Open (no hearts required)

Theoretically, you could expand this by applying other forms of requirements to access the mini-bosses buuuuut I don't think that really adds anything since the Shrine isn't an end-goal in seeds. Most people will end up just having it open but it doesn't hurt to offer the Vanilla option anyway since you made it work!

**Comment by ZoeyZolotova** [comment]
If it helps, here is a commit from MMR that altered the secret shrine door requirements. https://github.com/ZoeyZolotova/mm-rando/commit/8730439ea449edbb91a349be208a7561837ae595

**Comment by Revvenn** [comment]
Just gonna mark this as complete. If we want to add a setting to toggle for whatever reason to have the vanilla requirements that will be down to you. But most people found that experience not great so it being open by default and not toggleable is probably fine.
