### ISSUE TITLE
Setting: OoTxMM Progressive Behavior

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#113]
Basically a setting that allows the user to change the following (probably each with a checkbox?):

-Progressive Swords for OoT (when turned off, Swords are not progressive in OoT)
-Progressive Shields for OoT (when turned off, Shields are not progressive in OoT)
-Progressive Goron Lullaby (when turned off, the Goron Lullaby is not progressive and you get the full song right away but Elder Goron is still a check).
-Progressive Shields for MM (when turned off, Shields are not progressive in MM)

I think that's all this should include. The rest of the progressive items are how they normally behave in both randomizers, these are just the progressives you added that some people either like or don't like. The MM progressive shield is probably the least important because in MM there's only two shields anyway so it's not really a big deal either way as the other progressives added.

**Comment by Nax** [comment]
Done
