### ISSUE TITLE
OoT Setting: Kakariko Gate

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#114]
In OOTR there is a drop-down setting for the Kakariko Gate's behavior for a given seed. Here's the information, OoTxMM should have the same options (roughly). As a drop-down, of course.

-Open ("Open Gate": The gate is always open instead of
needing Zelda's Letter.)

-Zelda's Letter Opens the Gate ("Zelda's Letter Opens Gate": The gate is closed at
the start, but opens automatically upon obtaining Zelda's Letter.)

-Closed (current behavior)

**Comment by Nax** [comment]
I don't think we need `Zelda's Letter Opens the Gate` as we can have the letter AND other child items in the inventory.

**Comment by Revvenn** [comment]
> I don't think we need `Zelda's Letter Opens the Gate` as we can have the letter AND other child items in the inventory.

Yeah this was made waaaaaay before we had starting items.

**Comment by Nax** [comment]
So it turns out making the gate load as adult is pretty hard - right now we have `Open` which is exactly that, and `Closed` which is closed as child. The vanilla bug is also fixed.
