### ISSUE TITLE
Feature: A Way to Share the Same Seed with Others

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#115]
OOTR, MMR, and basically any other randomizer has some way to share the same seed with others as a smaller patch file. I think it would be nice if OOTxMM had the same option, be able to generate not just a seed but also a patch file for someone else to generate from the website with. For OOTR, they came up with a '.zpf' file. For MMR, they came up with a '.mmr' file. For DK64 Randomizer, they came up with a '.lanky' file.

It's to simplify sharing seeds if people were to race or co-op the same seed. It's essentially a better way to share seeds than having a seed number box to input and generate. Though, it may take more work to put this in than that seed number box it would be worth it in the long-term.

**Comment by Nax** [comment]
A seed input box would be a nice first step.
I cannot reuse the .zpf and .mmr formats, due to differences with the layouts of the games (since there are two of em) and so forth, but I could create a similar format for OoTMM.
It's pretty low on the priority list tho

**Comment by Revvenn** [comment]
> A seed input box would be a nice first step. I cannot reuse the .zpf and .mmr formats, due to differences with the layouts of the games (since there are two of em) and so forth, but I could create a similar format for OoTMM. It's pretty low on the priority list tho

Yep they were just examples, you can come up with your own file format and what not. And yes, low on the priorities for sure. I think this would be something that'd come after a bunch of settings implementations, quality of life, fixes, and hints. Just figured it'd be a good idea to lay this out there for later.

**Comment by Nax** [comment]
Seed input box done (patch format will come much later)
