### ISSUE TITLE
OoT Setting: Scrub Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#118]
Basically what the title says. Shuffle the rest of the scrubs with the following options as a drop-down:

-On (Affordable) - Makes every scrub cost 10 rupees

-On (Expensive) - All Scrub prices will be
their vanilla prices. This will require
spending over 1000 rupees on Scrubs.

-On (Random Prices) - 'Random Prices': All Scrub prices will be
between 0-99 rupees. This will on average
be very, very expensive overall.

**Comment by Nax** [comment]
Added for OoT.

**Comment by Nax** [comment]
Price will be a separate option
