### ISSUE TITLE
Setting: Cow Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#119]
Basically what it says in the title. Playing Epona's Song to any cow will give you an item instead of milk. You will need to get rid of the bottle-check requirement for MM cows, I think, but OoT cows iirc don't actually check for that? A drop-down setting that consists of the following options:

-OoT Cows (only the cows in OoT are shuffled)
-MM Cows (only the cows in MM are shuffled)
-All Cows (all the cows from both games are shuffled)

For the cows in OoT that are close together you will need to move them, OOTR does this so you can probably look at the old PR for how it was done: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/487

In MMR, there is a 'Close Cows' setting that essentially allows the player to milk the cows without having to actually move the cows. I think you can find this here: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/Cows.c -- perhaps if you can use this for the OoT cows you wouldn't have to move them? Would need to investigate.

As for how to represent cows are on in the item pool, in OOTR they don't add anything to the item pool (I think? You can look at the cow shuffle PR to confirm) but in MMR they add the equivalent amount of milk refills as there are cows in the game (which, if I remember correctly, would mean there's 8 Milk refills from MM cows). In addition, MMR made a recent change in how milk refill models look by taking the Red Potion model and coloring it all white with a blue strip around it, if you can do the same thing for the milk refill models that would be great (as the base game milk refills are bottle models and they are massive bait/obnoxious to see when you get a milk refill and it's not a bottle lol).

Cow Locations:

**OOT**
Gerudo Valley: by the river and soil as Child
Hyrule Field: under the grotto by the Gerudo Valley entrance, it's behind cobwebs you need to burn. As adult, you access the cow with hammer because there's a red boulder covering the grotto as adult while child can blow it up with a bomb (no boulder)
Lon Lon Ranch has 4 cows, two in the stable at the front and two in the back in the tower/silo
Kakariko Village: Impa's House (the Cow behind the cage in the house)
Link's House Cow (you win this cow from completing Malon's obstacle course as an adult)
Death Mountain Trail: Located in a grotto (a boulder is covering it) on the way to climbing up the wall towards Death Mountain Crater.

Total cows: 9

**MM**
Termina Field: There's a hidden grotto you use bombs or explosives to reveal that is located underneath the large wooden log structure on the way to the South. There's 2 cows in it
Great Bay Coast: On the way to Pirate's Fortress, on the ledges (the same area as the freestanding heart piece), there's an open grotto that you hookshot up onto the ledge to drop down into a lower ledge for 2 more cows in said grotto.
Romani Ranch: 3 cows are located in the barn night 1 (accessible at 6 pm and on) and by extension night 2 if you complete the aliens quest.
Beneath the Well: The cow is locked behind turning in 5 beans (or if you go in backwards you can skip the beans requirement), 10 deku nuts, and then hot spring water.

Total cows: 8

**Comment by Nax** [comment]
Fully implemented
