### ISSUE TITLE
Setting: Shop Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#123]
I understand this is probably going to be at the bottom of the list in terms of priorities but I felt we needed it on here as something to track. A setting that not only shuffles all the shops between the games but also their prices.

As for how OOTR handles price randomization this is what the Random setting for price says:

'Random': The default randomization. Shop prices for
shopsanity items will range between 0 to 300 rupees,
with a bias towards values slightly below the middle of the
range, in multiples of 5.

but OOTR also offers options for Wallet ranges that work like this:

'X Wallet': Shop prices for shopsanity items will range
between 0 and the specified wallet's maximum capacity,
in multiples of 5.

And OOTR also offers an Affordable option like scrubs where every shuffled shop item's price is 10 rupees.

As for what shops should be included in this setting for both games? Here's the list:

**OOT**

- [x] Kokiri Forest Shop
- [x] Castle Town Market Bazaar, Potion Shop, and Bombchu Shop (available at night)
- [x] Kakariko Village Bazaar and Potion Shop (Adult only)
- [x] Goron City Shop
- [x] Zora's Domain Shop

**MM**

- [x] Trading Post in West Clock Town (in MMR, the prices in the Trading Post change at night when the merchants change places from 9-10 pm, it would be so cool to have this part of this, too).
- [x] Bomb Shop in West Clock Town (the other two items)
- [x] Witch's Potion Shop in Southern Swamp (in MMR, selling the mushroom to Kotake allows you to get the Blue Potion for free which is vanilla behavior so anything in the Blue Potion slot can be gotten for free and will need Mask of Scents logic to use the mushroom for getting it)
- [x] Goron Village Shop (the prices in the vanilla game lower in Spring time, so you can make use of this functionality for further price randomization whether up or down)
- [x] Zora Hall Shop
- [ ] Milk Bar in East Clock Town (it's not a normal shop but I think it should be categorized here since it has 2 items they sell)

And if the price randomization settings can affect all of these that would be faaaaantastic. Understandably, like I said, expect this to be awhile before it's a thing. Reminder that for OOTR shops only one side is shuffled, the side with refills/tunics are not shuffled. Most players shuffle all 4 items as well so I really don't think we need to carry over those settings (as in we don't need to carry over 0, 1, 2, or 3 item shuffling). In fact, the settings breakdown could look like this:

Shop Shuffle: On
Price: (drop-down)
-Off/Vanilla prices
-Weighted Random
-'X' Wallet (or perhaps a Full Random, allowing for prices **above** 500 with the royal/tycoon wallets included)
-Affordable (every shop item is 10 rupees)

Shops
-OOT (only the OOT shops will be shuffled)
-MM (only the MM shops will be shuffled)
-All (All shops will be shuffled)

Also, the price randomization _could_ affect All Night Mask Purchase but only if you made the price randomization part affect it? I think ANM Purchase is just in the base item pool so to have the price rando affect it would be fun/nice but not needed if it's too much effort/work. The existing Bomb Shop Bomb Bags will need the price randomization, though (when the price setting is turned to on) since the other two bomb shop items would be included in this shuffle.

**Third Wallet**

A third wallet needs to be added for each game allowing you to hold 999 rupees total only when Shop Shuffle is turned on.

- [ ] Tycoon Wallet for OOT
- [ ] Royal Wallet for MM

**Comment by Revvenn** [comment]
An additional note: Probably should consider making the MM Blue Potion come back into your inventory in some way when you Song of Time reset or guarantee it is in a shop. Whichever is easier.

**Comment by Nax** [comment]
The base feature is done, tycoon wallet, price rando and the minor merchants can probably be their own settings
