### ISSUE TITLE
Feature: Hints System

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#125]
Bringing over the hints system from both OOTR and MMR. Gossip Stones (without Mask of Truth) will give you general direction on where required items are via Way of the Hero, Foolish hints to tell you what areas don't have required items, and some specific location hints like "Biggoron Crafts a Blue Rupee."

Few things to note:

-Always make hints the Clear version. It would be double the work to make vague, lore-style hints that are cool and fun but often get ditched immediately in favor of Clear hints.

-OOTR has WOTH-style hints but also other goal-style hints such as "Path to the Key" or "Path to the Tower" for instances where Ganon's Boss Key is shuffled or Trials are on. I'm not sure if we want to just go with Path hints from the get-go or if we should allow players to be able to specifically _set_ what style of hints they would like (whether Way of the Hero or Path). I could see Path hints being VERY GOOD for this randomizer, though, with hints like "Path to Odolwa" -- suddenly, you know that's either a bow, Sonata, Deku Mask, or some other item needed in that dungeon rather than the vague "Way of the Hero" which just tells you that region has required items in it. Path-style hints would also probably help Meds/Stones/Remains shuffle to anywhere and what not.

-Just make a Tournament-style hint distribution from the get-go. The default Balanced hint distribution OOTR has and OOT3DR copied doesn't really help either casual randomizer players or veterans of randomizers. Make the Tournament dist. the default and then expand on distributions as people play seeds. Given we are going to be able to use Gossip Stones across _both_ games we have a lot of flexibility in how the distribution's numbers should be.

Think that's all? Can discuss more when we actually start getting into this.

**Comment by Nax** [comment]
Implemented a large portion of it, we'll see if we need Path hints
