### ISSUE TITLE
QoL Setting: Fill Wallet

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#127]
Basically a setting where upon picking up a Wallet upgrade it will automatically fill your wallet to the max capacity you can hold at that time. So, if you have 0 rupees and then pick up an Adult Wallet it will fill your wallet with 200 rupees. Pick up a Giant's Wallet, it'll fill it to 500 rupees. So on and so forth.

Both Randomizers have different implementations of this but I think to keep things simple for us, it's better to have it as a Fill Wallet setting. I would look to how MMR does it (not sure where to find this on the git, though, so you would probably have to ask Zoey about it).

**Comment by Nax** [comment]
Done
