### ISSUE TITLE
Bug: MM Ocarina sounds turn into Deku Pipes after Sonata of Awakening Check

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#138]
Once you have checked Sonata of Awakening in Deku Palace when you use Ocarina, no matter what form you are in, will make the Deku Pipes instrument sound effects instead of whatever the normal Ocarina sounds are supposed to be for that form. It does fix itself after a Song of Time so it's a very minor bug but it exists nonetheless.

**Comment by Nax** [comment]
Fixed
