### ISSUE TITLE
Feature: Shared Inventory

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#149]
Basically the option to toggle whether items both games have are shared so when you get it for one game, you get it for the other. For example, getting Ice Arrows in OOT would then give you Ice Arrows in MM. Possibly multiple toggles so you can choose what you want shared.

- [x] Bow
- [x] Bomb Bag
- [x] Magic
- [x] Elemental Arrows
- [x] Hookshot
- [x] Lens of Truth
- [x] Ocarina
- [x] Keaton Mask
- [x] Bunny Hood
- [x] Zora Mask
- [x] Goron Mask
- [x] Mask of Truth
- [x] Wallet
- [x] Rupees
- [ ] Shields (Hylian <-> Hero, Mirror <-> Mirror)
- [ ] Kokiri Sword (**only** Kokiri Sword)
- [ ] Bombchus (if this isn't already a thing with Bombs? What would be interesting is if you made it so MM could use Chus without a bomb bag with this feature in order to properly support it? It could act as preliminary work for the Bombchu Bag later by having this set up with this?)
- [x] Deku Nuts and Sticks
- [ ] Magic Beans
- [x] Song of Time
- [x] Epona's Song
- [x] Song of Storms
- [ ] Empty Bottles? There's 2 empty bottles in both games and a bottle of Milk, these 3 could be the shared bottles.
- [x] Hearts

**Comment by Nax** [comment]
The remaining items are problematic and need special handling or other options first
