### ISSUE TITLE
Request: Clearer Build Instructions

### ISSUE THREAD

**Issue by daftinquisitor** [OoTMM/core#157]
Hi, sorry if this is not something on the radar right now. I'm trying to build the randomizer file here so I can play and do some testing / bug reports /etc, but as someone who's never used Docker, the steps in the read-me as is are not quite doing the job.

It mentions needing the OOT/MM rom files in a "ROMS" folder, but doesn't mention anything else about file structure. Also not mentioning how the Docker application is meant to be used to actually create the randomizer file. it has a simple command to plug in, sure, but again it doesn't mention how to set up to that point.

Any assistance on this would be peachy. I was looking for a Discord as well to check there for clearer info, but a link provided to someone else in another Issue is apparently an expired invite.

**Comment by daftinquisitor** [comment]
Update -- I managed to figure out how to use Docker to build the file (still think the instructions could be cleared up a bit), however now I'm getting an error when trying to run. I'm pretty sure both of my OOT and MM files are full header, but I'll double-check that in case that's contributing to the error.

failed to solve: executor failed running [/bin/sh -c apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes curl gnupg ca-certificates   && curl https://practicerom.com/public/packages/debian/pgp.pub | apt-key add -   && echo deb http://practicerom.com/public/packages/debian staging main >/etc/apt/sources.list.d/practicerom.list   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes     build-essential     n64-ultra     nodejs     npm     git   && useradd -ms /bin/bash ootmm]: exit code: 100

**Comment by zeldaking** [comment]
Same problem

**Comment by zeldaking** [comment]
I found a web generator of it that works. Its at https://ootmm.com/

**Comment by daftinquisitor** [comment]
Awesome, thanks! The GitHub page was the only thing that came up when I was googling, so I completely missed the webpage and discord. 

Probably wouldn't be a bad idea to add those to the ReadMe so people like me don't just run into a dead end here.

**Comment by Nax** [comment]
Not a huge priority right now - you can get help on how to build on the discord.
