### ISSUE TITLE
OOTxMM Setting: Chest Size and Texture Matches Contents

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#163]
This is for MUCH, MUCH later but basically the setting OOTR has where the size and textures match the contents in a chest, such as if you have a Gold Skulltula Token in a chest it'll be the cobweb covered texture or like if it's a major item then the metal outlines are gold and there's a triforce in the middle. Well, anyway, you can look at the textures OOTR uses but if you want to make your own that's fine too.

For MMR, all Zoey did was use wooden chests for junk (rupees, ammo, etc) and then the small gold chests (the small key chests) for trade items, potion refills, milk, and small keys. And then the bigger gold chests for major items (stuff like hookshot, masks, and what not). And then of course, Boss Key chests for BKs (the same is the case for OOTR).

Finally, if you want to, when dungeon rewards are shuffled you could also put those into BK chests since they are similar enough to BKs?

**Comment by Nax** [comment]
Done
