### ISSUE TITLE
OoT Bug: Empty Bomb

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#174]
Basically, in version 1.0 of OOT if you are walking/running forward while letting a bomb explode in your hands the game will consider you still having a bomb out. This prevents the player from opening a chest until they either hit the A button to "Put Away" the empty bomb or if they pull out another bomb then Link will automatically drop it. If either action is performed, then the chest can be opened and the empty bomb is gone.

It's a minor vanilla 1.0 bug that OOTR fixed so it should be fixed here as well. Here are the PRs for those fixes. This also can actually softlock you from receiving items from NPCs according to the PR below by fig02 which is uh, y i k e s if someone runs into that right now.

https://github.com/TestRunnerSRL/OoT-Randomizer/pull/268
https://github.com/TestRunnerSRL/OoT-Randomizer/pull/271

**Comment by Nax** [comment]
https://pastebin.com/L4qse0C0

Relevant documentation on the issue so I can fix it later

**Comment by Nax** [comment]
Fixed
