### ISSUE TITLE
MM Bug: Clock Town NPCs not making their traditional sound effects

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#175]
Self-explanatory, very minor bug (since it doesn't break anything) but many of the Clock Town NPCs (and some outside of Clock Town?) don't make their sound effects they normally do such as the toilet hand's "YAY!" or Anju's big sigh when you talk to her for the room key or Postman's "YAH" or the Bomber's little sound effect when they get caught, etc. etc.

Again, SUPER minor but just listing this here as I didn't put it up before.

**Comment by Nax** [comment]
Fixed by b9e4f51899221c966818744a15cdfb99d39851b8
