### ISSUE TITLE
MM: Skull Token Textbox not Autoclearing

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#176]
When Swamp and Ocean Tokens aren't shuffled in OOTxMM the textboxes require you to press A/B/any button to clear them right now. This is a very minor thing as it doesn't break anything but in vanilla MM (and in MMR when tokens aren't shuffled) the textboxes for collecting the Skull Tokens autoclear. When you are collecting items from skull checks in MMR, however, the game pauses upon collecting the item and you must clear the textbox to continue. I don't know if you *need* to do the latter but it is how it works in MMR. If you want to maintain the autoclear textboxes for when you get items from skull checks for MM then that also can work if it doesn't break anything.

This only became introduced with the new MM Token Shuffle settings.

**Comment by Nax** [comment]
Fixed (now pauses all the time, could be improved by autoclearing on tokens eventually).
Thanks zoey for the fix.
