### ISSUE TITLE
OOTxMM: D-Pad Restrictions

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#179]
Just as the title says. D-Pad items have the same restrictions as their C-button equivalents in the same scenes and etc. Made a separate issue so it doesn't get forgotten. This also includes preventing changing into Deku/Goron/Zora while wearing Giant's Mask or transforming while riding Epona.

**Comment by Revvenn** [comment]
In addition, in OOTR you are able to roll and equip boots with D-pad mid-roll but currently that isn't a thing in the combo rando. Would need to fix this so it's the same as OOTR.

**Comment by matthewkirby** [comment]
Adding to the ootr behavior revven mentions, not being able to use hovers mid roll/climb does hurt several fairly common tricks that people do. It was really weird constantly bonking because of this haha.

**Comment by Nax** [comment]
Fixed
