### ISSUE TITLE
OoT: Remove/Shorten/Skip last remaining cutscenes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#181]
The following cutscenes need to be removed/shortened/skipped:

- [x] Bottom of the Well Draining Cutscene (the one after you play Song of Storms inside the windmill)
- [x] Death Mountain Crater Intro Cutscene (when you first walk into the area from Goron City; going in from Trail does not trigger this scene)
- [x] Twinrova Boss Intro and Kotake and Koume Arguing scene
- [x] King Zora Mweeping Cutscene
- [x] Ruto inside Jabu, basically set her flag(s) so she's already in the basement. Also, the brief scene of her reaction to seeing the Zora Sapphire (this should somehow also be changed to reflect the respective dungeon reward but that's a separate issue) before the Big Octo mini-boss fight
- [x] Dodongo's Cavern after you blow up the first mud wall that shows the interior main room of the dungeon. I guess this is kind an intro cutscene of sorts?
- [x] Forest Temple Poe Sisters Cutscene (this is one of the glitch useful cutscenes, not sure how you want to remove it but then have it as an option later? Which by the way apparently the other glitch useful cutscene is the Darunia in Fire Temple cutscene so just a future note).
- [x] Owl Flying Cutscenes (already an issue set up for this, see #95 )
- [x] The cutscene when you drop the fish in front of Jabu and he eats Link
- [x] Morpha Boss Intro (set the flag for having died to the boss already or whatever)
- [x] Phantom Ganon Boss Intro (same as above)
- [x] Volvagia Boss Intro (same as above)
- [x] Bongo Bongo Boss Intro (same as above)
- [x] Kak Graveyard Royal Tomb Blowing Up cutscene (when you play Zelda's Lullaby to enter the Royal Tomb)
- [x] Gerudo Guards throwing you into jail, set the flag to have seen it already.
- [x] Warp Song Cutscenes (OOTR skips the scenes showing Link flying away, it just does some kind of fadeout, probably saves like 10 seconds or more. It also skips the flying in scene too)
- [x] Door of Time Opening Cutscene
- [x] Slingshot Target Give Item Cutscene

And I believe that's all? Hopefully didn't miss anything.

**Comment by Nax** [comment]
I edited your issue to turn the list into checkboxes so I can keep track of my progress

**Comment by Revvenn** [comment]
> I edited your issue to turn the list into checkboxes so I can keep track of my progress

Ahhh, yeah that makes sense I didn't notice I could have done that oops.

**Comment by Nax** [comment]
Boss deaths will have to be tracked separately (for twin and possibly phantom ganon/ganondorf) as they are way way more complicated, but also lower prio.

Otherwise, first batch of skips implemented by a240619ce6d5f14a1c3340540490249c209c9d85

**Comment by Nax** [comment]
Second batch added in `dab8e5dac745e9153476d758c406a16ff0f63277`

**Comment by Nax** [comment]
All done 👍
