### ISSUE TITLE
OoT: Decrease Radius of Lake Hylia Owl Grabbing you

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#190]
It was mentioned around a few days to a week ago that the Owl in Lake Hylia takes you away into its flying cutscene even if you walk all the way to the other side of the bridge. I think this was caused partially by the cutscene skip added? It sounds familiar to me happening in OOTR with its original implementation as well. Anyway, this needs to have its radius decreased so players can pull open the grave _in the future_ for when the scrubs in the grotto underneath the grave are shufflable.

It basically needs to be decreased down to his shadow or something? Or, maybe the cutscene trigger should only occur when you are in the owl's shadow, basically. Not sure what went on here exactly with the cutscene skip and this being introduced but they are definitely related as no one had reported this prior to the cutscene skip being added.

**Comment by Nax** [comment]
Fixed
