### ISSUE TITLE
Bug: MM Koume Pictobox check is affected by Boat Archery

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#191]
Apparently doing the Boat Archery check _before_ the Pictobox check will result in the Pictobox check having been counted as complete and you'll get a recovery heart for it instead of the item you're supposed to get? Was reported in #play-by-plays by Brads2000. Would need to be investigated to be 100% certain that's what's going on here.

**Comment by Nax** [comment]
I don't understand this, how can you even do boat archery before the picto check?

**Comment by Revvenn** [comment]
> I don't understand this, how can you even do boat archery before the picto check?

You clear WFT first without saving Koume in the pre-cleared WFT state. Meaning, the player made a conscious choice to skip healing Koume before beating WFT. As long as WFT is cleared, the check will always turn into Boat Archery. You do not have to have done the pre-WFT cleared Koume heal to be able to do Boat Archery; they aren't in sequence.

**Comment by Nax** [comment]
Okay. Right now I think I use vanilla flags for this check, I'll see what I can do.

**Comment by Nax** [comment]
Fixed
