### ISSUE TITLE
Feature: A Menu in the Pause Menu to track Dungeons Info such as Keys, Skulls, and Fairies as well as the Opposite Game's Inventory

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#194]
Now that keysanity has been added to the randomizer, this is a really handy menu both OOTR and MMR have in their respective randomizers. They basically have a menu that requires you to press an extra button to bring up on only the inventory screen, in OOTR it's the A button to bring up a menu that overlays on top of the inventory screen and it shows you all dungeon related info you need. In MMR, it's pressing the L button on the inventory screen to show you keys and stray fairies collected related to the dungeons. For this combo rando you can make it the same input for both games, really.

What the menu in OOTR looks like is attached here.
![153745221-736615ee-76fa-4905-9aa6-1f1fb0a62ad0](https://user-images.githubusercontent.com/40970119/212551518-994feb1b-ce0b-42aa-add7-5805d8634c95.png)

Would be nice to have now with keysanity and eventually Stray Fairy Shuffle. OOTR also has a setting that determines whether it shows you the dungeon reward info next to the dungeon names, not sure if you want to just make the dungeon rewards show by default or not but that's the only thing missing from the screenshot (that and a () showing the total number of keys you've collected *and* used next to the number in the screenshot which is total keys you currently *have* for the dungeon). The Boss Keys slot into the blank space after the small key numbers.

The skull icon is there to show you've collected all items tied to skulls/all the skull tokens in a given dungeon. Works like when you look at the dungeon map screen for the icon.

Anyway, just an example and maybe something you can just copy (not code-wise but visually).

Edit: In addition, some way to track in-game what the inventory screen for the opposite game has, maybe via some d-pad input when on the different screens? For example, OOT main inventory screen maybe pressing D-pad down on that screen will bring up a menu that shows what you have in the main MM inventory (so bow, hookshot, etc). Then, maybe on OOT's equipment screen pressing d-pad down will bring up a similar menu/overlay menu that shows your current MM masks. Then, on the overworld map screen (where dungeon map screen is as well) pressing d-pad down will show the various dungeon information shown above?

Alternatively, you could just make the d-pad directions left, down, and right show all this information on the main inventory screen of both games. Left could be masks/equipment (depending on which game you are in,), down could be opposite game's inventory, and right would be the dungeon info? It's a little complex because of just how much you can fit on these menus while also keeping in mind CRT overscan for N64 so you may not be able to fit *everything* for dungeon info on one menu? OOTR has a setup like this were A is generalized dungeon info and then it also has the d-pad menus for more specific information.

**Comment by matthewkirby** [comment]
I want to second that I think this is a massive QoL improvement and would absolutely love to see even a a rudimentary version of this. Needing to track keys/skulls/fairies across games can be difficult to miss which you just picked up and the only way to check is to hike out.

**Comment by Nax** [comment]
Done
