### ISSUE TITLE
Pause menu crashes game

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/core#198]
Please fix this! Whenever I pause the game to access the inventory menu in OoT, it crashes RetroArch. I don't like using GlideN64 since it's an outdated glitchy mess! It also crashes with GlideN64, but not as often as ParaLLEl RDP.

**Comment by Nax** [comment]
Emu issue, use the mupen core.

**Comment by 03bgood** [comment]
It still happens with Mupen64Plus-Next.

**Comment by Nax** [comment]
Make sure the Framerate option is set to "Original" ans not "Fullspeed" in the RA settings.
Also, this discussion should happen in the #tech-support channel on Discord, not here.
