### ISSUE TITLE
Small keys only count for WF

### ISSUE THREAD

**Issue by fbscarel** [OoTMM/core#2]
Testing a seed this morning, I got small keys on both SHT and GBT, but the key count kept at 0 (zero) and no doors could be opened. Going into WF, the first small key I got (pictured below) resulted in a "5" small key count, which makes it seem like small keys obtained in any MM temple only count for WF.

![image](https://user-images.githubusercontent.com/8995794/204093444-fd0521d9-6743-4769-9de4-12f51bcf1289.png)

Similarly, the only Boss Key that actually worked (i.e. found in the expected spot as per spoiler log and opened the Boss Door) was in WF as well.

**Comment by fbscarel** [comment]
To expand on this, once SoT is played the WF temple state is mostly reset (for example, the spinning flower goes back into the ground), but SHT -- centrall pillar -- and GBT -- valves -- are not reset after playing SoT. This is after playing SoT and going back into a partly-cleared GBT:

![image](https://user-images.githubusercontent.com/8995794/204093656-835bfa0b-e84e-4f26-8885-d200349baa3f.png)

Chests that should be re-openable after playing SoT -- like small keys and boss key chests in temples -- are left open, and keys can't be reacquired as is default behavior in the base game.

**Comment by Nax** [comment]
Small key issue fixed by #890b25.
Moving the flags problem to a new issue.
