### ISSUE TITLE
Bug: Tingle in MM is on the ground when you don't have magic

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#204]
I mentioned this in issue #64 but figure it should be its own issue to fix regardless. Basically, the vanilla game puts Tingle on the ground in the first cycle because you don't have a projectile to hit him down from the air. This behavior is achieved by magic, because when you have magic Tingle then becomes airborne everywhere. This behavior should be corrected such that he is always airborne (even when you don't have magic) in preparation for Tingle Map Shuffle.

**Comment by Nax** [comment]
Fixed
