### ISSUE TITLE
Bug: OOT Medigoron (Giant's Knife) Static Hint Textbox doesn't always work

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#208]
Basically, you will sometimes get OOT Medigoron's vanilla text and you either have to talk to him a second time for the modified textbox to appear or, you talk to the Gossip Stone first in the room _then_ Medigoron. Although, even then, it might not pop up and you still need to talk to him a second time.

**Comment by Nax** [comment]
Fixed
