### ISSUE TITLE
Bug: Cannot sell gold dust at curiosity shop

### ISSUE THREAD

**Issue by ludvigng** [OoTMM/core#210]
Hello!

Currently the curiosity shop will not accept selling gold dust. In the vanilla game, you can sell gold dust for 200 rupees.

**Comment by Revvenn** [comment]
This isn't a bug this is intended behavior. You can only turn in Gold Dust to the smithy, it's like Ruto's Letter. This is because you can find Gold Dust in OOT and it comes back into your inventory every cycle until you turn it into the smithy.

**Comment by Nax** [comment]
Yeah it's the current solution to prevent losing gold dust permanently. It's not incredible but it's intended behavior and not a bug.

**Comment by ludvigng** [comment]
Yeah, that makes sense, thanks! Although it is frustrating when it's the only bottle available before having access to the smithy. Hopefully there's a different solution available in the future. :)
