### ISSUE TITLE
Bug: MM C-Buttons and the B button disappears upon collecting randomized freestanding Stray Fairies

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#211]
This is a minor bug with Stray Fairy shuffle where when you collect randomized freestanding Stray Fairies. When you collect the randomized item, the some of the UI fades out (C-Buttons, B button) until you pause and unpause or open a chest. This was also a bug in MMR for awhile with the Clock Town stray fairy. You maaay need to talk to Zoey about how she fixed it? Doesn't cause any issues, just makes some of the UI disappear for a bit.

Edit: This also occurs when freestanding Stray Fairies are vanilla. So it's just freestanding fairies at all right now.

**Comment by Nax** [comment]
Also fixed by the pause thing zoey added
