### ISSUE TITLE
Setting: Boss Entrance Shuffle/Randomization

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#215]
**Considerations/Adjustments Needed for Setting**

- [x] First, we need to prevent save warping putting you in the dungeon the boss is from. It needs to respect the parent dungeon such that if you are in Gohma's boss room while Gohma was in Spirit Temple, when you save warp, it will put you back in Spirit Temple and _not_ Deku Tree. The same is the case for dying.
- [ ] Twinmold's boss arena has a void out zone at the edges. This void out zone needs to put you at the entrance of the parent dungeon and _not_ Stone Tower Temple. (It might already function this way if the void out is literally just checking for your last loading zone you walked through? Needs testing either way). For cross game shuffle, this is going to need a different consideration for how to handle. Or, perhaps in Boss ER only the MM Dungeon bosses have a spawn point?
- [x] MM Bosses need to follow the behavior of their parent dungeon they are in. Such that when you beat say, Odolwa at Snowhead Temple it triggers the Snowhead post-dungeon clear flags and spits you out at Mountain Village in Spring Time.
- [x] OOT Bosses need to follow the behavior of their parent dungeon they are in when you step into the blue warps. Dodongo's Cavern's boss blue warp, for example, needs to send you to Death Mountain Trail and _not_ whatever location the shuffled boss was in (i.e if you beat Twinrova, it sending you to Colossus. It needs to send you to the parent dungeon's original destination from the blue warp).
- [x] Handling Morpha. You may need to create the Gossip Stone in Lake Hylia to raise/lower the water level with a sword slash once Morpha has been killed. Morpha clear activates the Lake Hylia water level raising and this is true even in OOTR's implementation of boss shuffle. This will need to be added regardless for other forms of ER to prevent softlocks with Gold Scale entry. Refer to OOTR about the location of where exactly the stone should be because the spot they put it in was to specifically avoid messing up people with glitch/trick setups and what not.
- [x] Hints need to respect the parent dungeon, such that if you get a WOTH Deku Tree and the boss there is King Dodongo, the chest before dropping down into the actual boss fight would count towards Deku Tree's region in this case _not_ Dodongo's Cavern. Same thing for the Heart Container of the boss.
- [x] May need to handle exiting certain boss doors (like Deku Tree from Gohma's boss room, the door just before you walk into the arena and get locked in to fight Gohma). There's very few of these in fact Gohma might be the only one? Okay also King Dodongo's door on the same floor as the chest needs to be considered. You cannot leave any of the arenas in MM via the doors, though.
- [ ] Dying to MM bosses needs to be handled when Cross Game shuffle is enabled. Same for Song of Time. Edit: Dying seems to work fine, you end up spawned back in the boss' lair. So you really only need to handle Song of Time.
- [x] The dungeon reward/clear in MM needs to respect the parent dungeon as well so the boss warp will activate and take you to the boss. I.E when you beat Twinmold at Woodfall Temple the boss warp in WFT will activate and take you to Twinmold. This part may become more complex when #195 is an option, but then I suppose when you pick that setting with Boss ER you know what you're getting into.
- [x] Logic and algorithm for Boss ER.
- [x] Soaring works in boss rooms, need a way to handle it. Send back to parent dungeon in Own Game, but Cross Game...? Or, disable soaring... for cross game??? I don't know. Edit: Apparently the way things currently work, your spawn point in MM is when you first enter it so when you enter a boss room from OOT and you try to Soar, it functions as if you actually set a spawn point at the boss door in the lair; it just puts you right back in the boss room when you try to soar right now. Whether we want to change this behavior at all is entirely up to you but when it's MM -> MM Boss it functions as normal (can soar out of the boss room and to the dungeon's entrance). So the behavior is working how we theorized it should already and doesn't break anything unless you consider the OOT -> MM boss functionality to not be _exactly_ how you want it.

But otherwise it means MM won't be forced to Song of Time out when entering from MM to a MM boss which is good since MM can't save anytime. Most players playing this feature will likely save at an owl statue before entering a given dungeon but this extra bit of timesaving is nice (so you can just leave the dungeon normally).

**Settings**
- [x] Own Game. Basically, restricting the bosses to shuffle within their own game. Whether or not you want to split this up further with OOT by having Age-restricted (so child only fights child bosses, adult fights only adult bosses) and Full is entirely up to you.
- [x] Cross Game. Allowing bosses to be shuffled between the two games such that when you walk into the Deku Tree Boss Room, it can load into MM and put you in Odolwa's boss room. And walking into Great Bay Temple's boss room loads into OOT and it loads a child boss like Gohma, making you child Link.
- [ ] Age-restricted. Basically, a setting that still shuffles the bosses between the two games but instead Adult OOT bosses can only be shuffled among adult OOT bosses so Child doesn't end up getting Bongo/Phantom Ganon. Limits the shuffling to basically Child bosses with MM Bosses (so strictly Gohma, KD, Barinade with Odolwa, Goht, Gyorg, and Twinmold).

I think this covers the tasks for this feature? I can't think of anything else.

**Comment by Nax** [comment]
(The Morpha behavior was tied to the dungeon and not the boss for consistency with MM - also no water level switch yet as gold scale entry is not logical, but could be a separate issue)

**Comment by Nax** [comment]
Current implementation seems to work fine, unsure if we want more options?
Age-restricted would change very little.
