### ISSUE TITLE
Setting: Dungeon Entrance Shuffle/Randomization

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#216]
Since Boss ER is being looked into, I think this is the next step up from that that's probably just as (relatively speaking) easy to implement?

**Considerations/Adjustments Needed for Feature**

- [ ] The dungeons save warps (as well as dying) need to put you inside the dungeon it's been shuffled to, not the original dungeon you entered from (this may not even need special handling and may just be fine as-is, needs testing).
- [ ] Boss warps, if bosses are vanilla or shuffled, need to send you to the parent dungeon's post-dungeon clear destination (so i.e if it's Dodongo's Cavern at Spirit Temple it needs to send you to Desert Colossus and not Death Mountain Trail). I suppose this is even the case when bosses are shuffled as well with this setting so if you had Dodongo's Cavern at Spirit Temple but the boss is Gohma inside DC then it should still send you to Desert Colossus.
- [ ] Boss warps need to respect the parent dungeon's post-dungeon clear flags as well, except in the case of Water Temple? Since it's Morpha that controls the water level as mentioned in the boss ER issue. Anyway, basically what should happen is when you step into the Forest Temple and Forest Temple is Fire Temple and whether the boss is vanilla or shuffled, once clearing Fire Temple inside Forest, Kokiri Forest should be in its post-dungeon clear state (where the enemies are all gone from the scene). Likewise, if you enter Snowhead Temple and the dungeon at Snowhead Temple is Inverted Stone Tower Temple, it should make it Spring Time whether the boss is vanilla or shuffled inside ISTT inside Snowhead Temple.
- [ ] In MM, Stone Tower Temple is two entrances. In MMR, it was decided to only shuffle Inverted Stone Tower Temple because that's where the boss is while Uninverted Stone Tower Temple is left vanilla. But shuffling Uninverted Stone Tower Temple's entrance would be interesting so would like to see it for both Own Game and Cross Game options. Edit: The idea for this is to only shuffle it with the other side dungeons from OOT which would be: Bottom of the Well, GTG, and Ice Cavern since it doesn't have a boss blue warp in it to allow it to clear regions in MM. And by extension also possibly include the spider houses in this mix? It was an extensive discussion. To note, child cannot do Ice Cavern without the blue fire shop logic as he cannot reach the dungeon map room due to his height.
- [ ] Deku Princess Room needs to **always** be at whatever dungeon replaces Woodfall Temple, i.e if it was Shadow Temple at Woodfall Temple then the blue warp inside Shadow Temple needs to send to Deku Princess Room (which is functionally sending you to the post-dungeon clear area anyway like the other blue warps inside MM dungeons would do). And by extension, then, set the post-dungeon clear flags as said above. So logic needs to assure that it is possible to get the Deku Princess when you do not start with a sword.
- [ ] Death Mountain Crater's silver boulders as child need to be turned into small rocks or otherwise, removed. This would give child in OOT another dungeon to access in dungeon ER
- [ ] The Well in Kakariko Village needs to be drained properly in adult age when child plays Song of Storms so adult and child can have another dungeon to access in dungeon ER (this helps with Spirit Temple placement).
- [ ] Deku Tree needs to have its mouth open (with Open Deku Tree setting) as adult so adult can access Deku Tree as well (if this isn't already a thing, I'm not 100% sure on this right now). When Closed Deku Tree is introduced, this behavior will differ as it will require the Tree to only have its mouth open for adult when you have moved Mido as child with the Kokiri Sword and Deku Shield **if** you have Closed Deku selected.
- [ ] The Spirit Temple hands need to continue to send to Desert Colossus when you exit from their respective exits in Spirit Temple. This also needs to be considered in logic as a way to get out to the dungeon in Desert Colossus _and_ as a way to get out to Colossus in general.

**Settings**

- [ ] Own Game. Basically, the dungeon entrances shuffle within their own game.
- [ ] Cross Game. The dungeons shuffle between the two games.

Once again, I think this is all for this feature? I can't think of anything else.

**Comment by Nax** [comment]
Done (with some differences, as talked about in the discord).
The extra dungeon access (Deku as adult, etc.) will be added in a later commit.
You can move that to a new issue if you want!
