### ISSUE TITLE
 Crashing every time when I try to do majora mask on mobile

### ISSUE THREAD

**Issue by Loganlanner1** [OoTMM/core#223]

**Comment by Revvenn** [comment]
The combo randomizer does not play on mobile. All mobile emulators are going to crash when going to Majora's Mask because they do not use the latest version of mupen. If you want to play this at all you need to play on a desktop computer.

**Comment by Loganlanner1** [comment]
Oh can you try to do it like on mobile I always I wanna try to do it on mobile I think it would be fun doing it on mobile

**Comment by Revvenn** [comment]
> Oh can you try to do it like on mobile I always I wanna try to do it on mobile I think it would be fun doing it on mobile

It is out of our hands. You would have to ask the people who make the emulators on mobile to update their mupen cores. OOTMM is not compatible with older versions of mupen.

**Comment by Loganlanner1** [comment]
I go to  do it

**Comment by Loganlanner1** [comment]
M64plus FZ

**Comment by Loganlanner1** [comment]
That the Emilator play on
