### ISSUE TITLE
Bug: On Everdrive, unable to equip C-items after coming from MM

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#225]
This bug has only been reported by Joshua as I can't seem to replicate it from the web generator. I tried going from MM back to OOT, I was able to equip items in Market as child. So then I went to ToT and turned adult and was still able to equip C-items; my pause screen did not grey out the C-buttons. According to Joshua that's what his pause screen does when he can't do this.

I'm putting this up as something to look into, I don't really know the full details and since it doesn't happen to me it might be an offline build only issue of some kind?

Edit: Joshua did some testing and with his version of the offline build this is the case for him but warp songs don't crash while on webgen C-items are fine and warp songs crash. Could these be related? I don't know.

**Comment by Nax** [comment]
Seems to be solved by recent changes.
Not sure why to be honest, it's possible something else is broken.
