### ISSUE TITLE
Bug: Transition on ED is less smooth after recent ED changes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#232]
I know you said you'd revert the most recent ED attempts at fixing next time you go to try to fix it again, just putting this here as a reminder. Basically, at least for me from webgen on Dev, my TV's NO SIGNAL pops up for 1 second when going from MM back to OOT instead of remaining black the entire time like before. Not sure which commit caused this change "cache changes" or "ED small fix" but it wasn't like this on what's currently the Stable version and it was working the same as Stable before those 2 commits. The commits in question were versions [b2fe3ec](https://github.com/OoTMM/core/commit/b2fe3ecde491cfeae835c9ea3823e1136c3fc4da) and [33919b6](https://github.com/OoTMM/core/commit/33919b69111035826744db12a3faa04adaa4b09a)

**Comment by Nax** [comment]
Pushed a fix on dev for that.
Can't really test it myself as my TV takes a very long time to display a "No Signal" prompt.

Closing now, feel free to reopen if it turns out not to be fixed.
