### ISSUE TITLE
QoL suggestions

### ISSUE THREAD

**Issue by fbscarel** [OoTMM/core#24]
Kind of a meta-issue, but these would massively improve running seeds in a single seating (max 5~6h runtime). Ideally as configuration options, so as not to make any one setting mandatory for all users:

- Customize starting items, **ESPECIALLY** starting Ocarina and Prelude/Soaring to avoid useless backtracking.
- Make OoT Adult instantly accessible (i.e. Open Door of Time) from seed start.
- Disable Songsanity (i.e. all songs are acquired on their original locations, but song rewards can be from either game).
- Closed Deku Tree, so as to avoid "cookie-cutter" openings. Random spawns would add to this, but obviously more complex to implement.
- Skip borderline non-gameplay sections, e.g. Zelda "Child Stealth" sequence, Epona Race, two-minigame phases (Dampé Race, Horseback Archery, basically all MM minigames).
- Remove stray fairy chests from MM dungeon pool, emulating S1 distribution.
- Make checks removable from general pool, especially those that are way too time-consuming for such a long marathon (e.g. Aliens/Cremia, Spider Houses, Goron Race, 40/50 GS, Biggoron trade items, etc.).
- Hints in Gossip Stones.

**Comment by Nax** [comment]
Most of these are done, the rest have their own issues now :)
