### ISSUE TITLE
Bug: MM Credits Sequence cannot proceed due to Igos Intro Cutscene Skip

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#244]
As I reported in discord, I totally forgot to tell you this for the initial implementation of the cutscene skip. But anyway when the credits hits the scene with Igos and his men's heads floating around and stuff it instead initiates the boss intro cutscene skip and actually loads the fight in the credits sequence. This results in the credits sequence not being able to proceed as it's hit some kind of "gameplay" and the screen turns red with combat music playing. MMR had this same issue when skipping this cutscene affecting the credits in the exact same manner and Zoey fixed it so I'm sure it's fixable here.

**Comment by Nax** [comment]
Done
