### ISSUE TITLE
MM Settings: Majora Child Requirements

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#249]
Much like the Ganon Boss Key settings for OOTR, this would be more useful for when issue #68 MM Settings: Moon Access Requirements is implemented. Basically, Majora Child would check for your goal/win condition settings and determine whether you can fight Majora or not. This would help the setting/option with Moon Access if an Open setting was created/added, much like there is one for the Rainbow Bridge. In addition, it would allow someone to have extra requirements in the seed if they, for example, decided they wanted all remains to get onto the Moon but then All Masks to fight Majora.

This would ultimately have the same options available as mentioned in the Moon Access Requirements issue with one other exception: Vanilla. Vanilla for Majora Child would be that you'd need nothing to fight Majora, he would be fightable as soon as you decide you want to fight him. Some people might like that anyway so offering it seems sensible. And, well, it pairs well with the Vanilla Moon Access Requirements anyway (since having both of those would mirror the current behavior for MM).

**Comment by Nax** [comment]
Added
