### ISSUE TITLE
OoT Settings: Additional Ganon Boss Key Settings

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#250]
Basically, once issue #67 is implemented add the same settings from there to Ganon Boss Key and to receive Ganon's Boss Key anywhere once you meet the requirements selected. So, for example, if you get all 6 medallions (if that's your GBK setting) then the game will give you Ganon's Boss Key, even if you save + quit before actually entering into the Get Item animation. So as soon as you go back into the file it should still give you the GBK. Cuphat implemented this here for OOTR: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1367 (this way you won't lose the key no matter what)

**Comment by Nax** [comment]
Added
