### ISSUE TITLE
Bug (kind of): Captain Keeta ending cutscene skip forces Link to run off the ledge

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#277]
Basically, whether you are wearing Bunny Hood or not the cutscene skip introduced for Captain Keeta spawns Link running off the ledge, somewhat defeating the purpose of the cutscene skip _if_ you don't have Goron Mask. It makes you have to run alllll the way back around since you fall off and all.

**Comment by Nax** [comment]
Fixed
