### ISSUE TITLE
Internal cartridge saving

### ISSUE THREAD

**Issue by PapiJona** [OoTMM/core#301]
It's possible to add an internal save feature to play on real n64 hardware without a memory pack?

**Comment by Revvenn** [comment]
You can play on real N64 hardware but you can't play it on an Everdrive 2.5 or X5. It needs to be a V3 or X7 and you have to set the save type to FLASH.

**Comment by PapiJona** [comment]
Thanks, now I can save.

But now when restarting my file all the items are in the same places as in the original games 
Any suggestions?

**Comment by Revvenn** [comment]
I'd really suggest joining the discord for further help (https://discord.gg/4QdtPBP6wf), the only other thing you can do is updating your OS **IF** you are on an X7 or V3 (V3 has to use the OS version 3.05 or something). If you aren't, if you are on a 2.5 and/or X5 (or a Chinese knock-off which typically is based on one of those versions), it will not work for you no matter what you do. Items will be vanilla no matter what.
