### ISSUE TITLE
OoT: Add the ability to warp to MM via playing Song of Soaring

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#304]
As discussed in #dev-talk, a setting the user can decide on how they want Song of Soaring to function in OoT that when played sends you to the Clock Tower Entrance in South Clock Town with a drop-down that consists of the following options:

OoT Soaring:
-None
-Child Only
-Child and Adult

This would, in the meantime, allow for MM dungeons to have Adult dungeons in ER and give Adult Link access to MM where currently he does not. This would be a good solution until an official entrance exists for Adult without Song of Soaring. There's also interesting logic in place if you shuffle Song of Soaring as it would mean MM adult access is logically locked behind Soaring. Also, ideally, the warp animation uses white colored sparkles to match the fact Soaring has white feathers in its warp animation.

This was brought up because Zoey has PR'd a OOT warp songs working in MM to warp to OOT song locations. The equivalence to that on the OOT side is Song of Soaring warping to MM; a first version of this would be what I described above. Maybe in the future it would be possible to have the Soaring allow you to select from the owl statues you have active in MM but for now the above functionality would be just fine right now (taking you to South Clock Town Clock Tower Entrance). Would make sense to have!

**Comment by Nax** [comment]
Added
