### ISSUE TITLE
Feature - Have a Checkmark icon when an area on world map has no more checks if player has that area map

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OoTMM/core#326]
Using 3rd party tools can be really annoying ... it would be nice if we could have some ingame indication that something has been picked clean.

**Comment by Revvenn** [comment]
This would be an unreal amount of work for something that not a lot of people would actually use; specifically because the game actually doesn't even keep track of what we consider to be "checks." The third party tools exist for a reason, use them.
