### ISSUE TITLE
Feature - Add a way to disable tatl navi c up or make them say a hint that leads to progression when in logic.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OoTMM/core#327]

**Comment by Revvenn** [comment]
The first idea while might be okay to have as an option, not even OOTR has it, so if it did happen it would be extremely low priority. Very, very far down the bucket list. Not adding this to the list right now. Navi's pretty ignorable majority of the time. The second idea is just completely unnecessary when Gossip Stones exist. Finally, there's no way to give you a hint for something "when it's in logic", without what I would assume would be an absurd amount of coding for little gain. Map trackers or Zeik's check list tracker in tandem with the existing Gossip Stone hints is plenty enough to tell you what's in logic with your current item set.
