### ISSUE TITLE
Bug: MM Short Hookshot when on C-button doesn't update to MM Hookshot when obtaining it

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#330]
What the title says. If you have MM Short Hookshot on a C-button and get MM's Hookshot (the longshot progressive upgrade basically) the short hookshot won't auto update to the full hookshot on the C-button. Not sure if it matters if it's found in MM or OOT but when I saw Ghun play with it, he found MM Hookshot inside MM and he had the Short Hook on a C-button and it didn't update; he had to reequip the Hookshot for it to update.

**Comment by Nax** [comment]
Fixed
