### ISSUE TITLE
Website Feature: Presets

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#331]
Xopar was originally working on this a few weeks ago but he's become too busy to implement it and felt what he was doing anyway wasn't the best. Now that there's a lot more settings to turn on and configure it would be nice to have this feature. Basically, a website feature to save your settings under a specific Preset name so you can have multiple settings to swap between. The presets drop-down could include a preset by default, maybe the current default settings are the first preset and then anything beneath that are the ones the user creates?

How these are stored on a user-basis I wouldn't have a clue but ZOOTR has this feature for their web generator so there must be a way to do it here, too? Anyway, it would be nice to hotswap between settings instead of having things where you might forget to turn on/off something, including tricks, and what not.

**Comment by Nax** [comment]
Added
