### ISSUE TITLE
Setting: Tycoon and Royal Wallets

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#336]
A setting players can toggle to add both the Tycoon Wallet (for OOT) and the Royal Wallet (for MM) that acts as a third wallet upgrade, bringing the total max rupee capacity for both to 999 respectively. This setting is primarily intended to be used for Shop Shuffle but having it separate means players can have an optional third wallet in the pool without Shop Shuffle being on.

- [x] Tycoon Wallet
- [x] Royal Wallet

**Comment by Nax** [comment]
Added
