### ISSUE TITLE
Bug: Lake Hylia Owl does not fly away after spoken to

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#340]
This is a known bug but this will need to be fixed for the incoming Scrub Shuffle setting. Basically, you normally use the Owl to fly back to in front of Hyrule Market and if you choose not to use him by standing far away from him he usually flies away after some amount of time. But in combo right now, he just gets stuck in an infinite loop of starting to fly away but never does. While you *can* still get into the grave, most players that have tried to get in end up thinking they can't or they don't do it correctly and get flown to in front of Hyrule Market. This issue needs to be fixed so the Owl will properly fly away when you are standing away from him.

**Comment by Nax** [comment]
Fixed
