### ISSUE TITLE
Bug: Scrubs won't sell you Bombs

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#350]
Basically the same issue shops had where scrubs won't sell you explosives unless you've cleared Dodongo's Cavern. Apparently this is still an issue? I thought you would have addressed this with scrub shuffle but someone in discord reported having it happen in a recent seed.

**Comment by P3rf3ctXZer0** [comment]
Glad I didn't do scrubsanity yet ... I almost started a dev seed yesterday. Thanks for reporting.

**Comment by Nax** [comment]
Pretty sure it's not a thing - I replaced the whole function that checks for requirements for scrubs with the same one I use for shops, and in my testing I bought bombs fine (I had bomb bag but not DC clear).

**Comment by Revvenn** [comment]
> Pretty sure it's not a thing - I replaced the whole function that checks for requirements for scrubs with the same one I use for shops, and in my testing I bought bombs fine (I had bomb bag but not DC clear).

Ah then the person must have been referring to an older seed without scrub shuffle, probably from weeks ago I'd hazard a guess. I'll close this issue then until more people report it as an issue. I sort of jumped the gun I guess, I dunno lol.
