### ISSUE TITLE
All inventory in MM shows an ocarina, and some items didn't transfer

### ISSUE THREAD

**Issue by link259** [OoTMM/core#371]
When I first entered MM everything was an ocarina. I assumed this was due to me not having one yet so when I finally had one and went back to MM I was concerned when I still saw most of my inventory was still ocarinas but some of the slots were filled correctly. That being said I was a little closer to playing MM since I could use some of my items. However, only roughly half of my orders were there. I should have had a deku mask, gorons lullaby, a hookshot etc that I had previously picked up but all those items weren't available. I double checked the spoiler log and went back to the locations I got them and  they were still looted so its not like I forgot to pick them up or loaded a wrong save

**Comment by Nax** [comment]
What emulator (including the version) are you using?

**Comment by link259** [comment]
Bizhawk 2.3

**Comment by Nax** [comment]
Don't use bizhawk, their N64 is 10 years old and severely broken.
