### ISSUE TITLE
Setting: Dungeon Rewards Shuffled to Any Dungeon

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#377]
What it says in the title. A new setting under Dungeon Reward shuffle that restricts them being shuffled to Any Dungeon, which would also include what we've qualified as dungeons in Dungeon ER (so like spider houses, Beneath the Well, Ikana Castle, Pirate's Fortress etc). I'm not sure if you want to restrict it to one per dungeon like the Dungeon Blue Warps setting or if you want it to be unrestricted and allow any number to be in any dungeon. Probably whatever sounds better? Or you could do both and just have it designated like so:

Any Dungeon (Restricted)
Any Dungeon (Unrestricted)

But I dunno. Anyway, would really love to see this setting!

**Comment by Nax** [comment]
Done
