### ISSUE TITLE
"Logic: Probabilistic Foolish Analysis (can take up to a few minutes...)"

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/core#386]
It won't load the randomizer on the website. It just gets stuck on this message!

**Comment by Nax** [comment]
How long did you wait?

**Comment by 03bgood** [comment]
> 

I dunno.

**Comment by Nax** [comment]
Try waiting a bit more.

**Comment by 03bgood** [comment]
Okay, now it's loading more.
