### ISSUE TITLE
OoT diving in the lab softlock

### ISSUE THREAD

**Issue by fbscarel** [OoTMM/core#46]
Not sure what triggers this condition (possibly acquiring the vanilla HP elsewhere?) but I just got locked out of a seed where MM SoT was in OoT Diving in the Lab, and after doing it with Gold Scale the item was never given by the NPC. Ref.: https://www.twitch.tv/videos/1665697767?t=66m15s

(this is using the lastest commit from the `develop` build as of this post)

**Comment by Nax** [comment]
Did you have the eyeball frog by any chance?

**Comment by fbscarel** [comment]
Not sure, I'd have to go thru the VOD to say for certain.
