### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by Onemario1234** [OoTMM/core#53]
I know this is not the right place for a post like this, and I'm sorry in advance. I just wanted to suggest something like this and have nowhere else to turn to.

This is just a suggestion, so you're free to ignore and close this, but perhaps opening a Discord server with a link in the README would be a good idea? That way people can talk about this Randomizer, ask for help in setting it up, etc. Because as it stands, I don't know how to set this up and have no one to consult. Plus, setting up a little community would help this Randomizer gain traction.

**Comment by Nax** [comment]
This is indeed not the right place for this, but it's okay.
We have a discord server already, you can find it here: https://discord.gg/3g8EYJMcpc
This should probably be added to the README indeed.
