### ISSUE TITLE
OOT: D-Pad Functionality

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#62]
Bringing D-Pad Functionality from OOTR which includes the following:

The D-Pad being on the right side of the screen under your C-buttons.

Adult:
-Iron Boots on D-Pad Left
-Hover Boots on D-Pad Right
-Ocarina on D-Pad Down

Child:
-Child Trade Items/Masks on D-Pad Right (the current one in your inventory is what the D-Pad will use, so if you have Bunny Hood selected in the inventory then the D-Pad will reflect that. When you press L in the inventory it would ideally update to the next child trade item. I am aware that currently it requires you to re-equip the trade item to your C button but surely the D-Pad can auto-update the item?)
-Ocarina on D-Pad Down

There will have to be a few things to be aware of when putting this together. Some restrictions have to be put into place for boots and ocarina while on the D-pad like this old pull request for OOTR shows for ocarina here: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/504

And also this where you hookshot while using d-pad boots: https://github.com/TestRunnerSRL/OoT-Randomizer/issues/546

Just in case when referencing how this was made these don't get missed. Not sure if there are any other restrictions that need to be accounted for but I'd imagine these things are probably in the code for all of the D-Pad functionality when you go to look at it in the OOTR repo.

**Comment by Nax** [comment]
👍 
Implemented as of a0f508afb45afd97ab5b8e4af7de81fd8526f56e
There are probably a bunch of issues that will arise from the dpad, but these will be tracked separately.
