### ISSUE TITLE
Shuffle: MM Tingle Maps

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#64]
Just putting this here as a TODO, shuffling the Tingle Maps in MM. In addition, Tingle needs to be fixed so he is always airborne (is tied to Ocarina being shuffled and the flag tied with that). And text for the items he is selling will need to be updated accordingly (but you said this would be no issue, just putting it here in the issue to make sure it is not forgotten).

Edit: Tingle should also be affected by price randomization (when turned on) and the prices should differ depending on the tingle location you're buying from, so North Clock Town Tingle's prices will differ from Road to Southern Swamp Tingle's.

Edit 2: The settings should probably mirror maps/compasses shuffle where you can:

Off/Vanilla
Shuffled
Starting With/Items (OR, if you don't want to make this a setting and just have the above two we can just use the existing Starting Items section to choose to start with Tingle Maps).

I don't think removed should be included but if you want to I guess lol.

**Comment by Nax** [comment]
Done
