### ISSUE TITLE
OoT Settings: Open Door of Time

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#66]
What it says in the title. The Door of Time is open and the Master Sword is not shuffled (you start with it like normal). The dungeon reward (or item if dungeon rewards are shuffled to anywhere/overworld only/any dungeon) you receive from this could be collected when you enter the Temple of Time at the Master Sword location like normal, that function doesn't need to change.

Edit: If you wanted to provide more settings for the Door of Time you could turn this into a drop-down with the following:

-Closed (current functionality)
-Open
-Intended (so you need the 3 stones, Ocarina of Time, Song of Time, and Master Sword)
-Variable stones (so you only need anywhere between 1-3 stones, maybe only applicable somehow to Intended *or* the setting below).
-Only Ocarina and Song of Time (Master Sword is forced vanilla?)

**Comment by Nax** [comment]
Done
