### ISSUE TITLE
OoT Settings: Rainbow Bridge Requirements

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#67]
Allow players to set the Rainbow Bridge to the following requirements:

-Open
-Vanilla Requirements (Spirit/Shadow Medallions and Light Arrows)
-Spiritual Stones 
-Medallions
-Dungeon Rewards (this allows you to collect either Medallions or Stones to count towards a total needed for the bridge to open, for example, if you set it to 5 dungeon rewards then you can collect 3 stones and 2 medallions or 3 medallions and 2 stones, etc, this would also be able to include Remains if possible)
-Gold Skulltula Tokens (this is only really relevant when Gold Skull Tokens can be shuffled)
-Hearts (up to 20 hearts to open the bridge).
-Swamp and Ocean Skulltula Tokens (up to 60)
-All Tokens (up to 160)
-All Stray Fairies (up to 61)
-All Tokens and Fairies (up to 221)

With the exception of Open and Vanilla Requirements, all of these have configurable sliders for the amounts needed for the bridge. For example, while normally the default is 6 medallions you can lower the amount of medallions to 2 for the bridge to open if you want. Gold Skull Tokens can be configured from as low to 1 to 100, hearts from 4 to 20, etc etc.

**Comment by Nax** [comment]
Added most of this
