### ISSUE TITLE
MM Settings: Moon Access Requirements

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#68]
So The Moon is pretty tricky, I'm not sure how much we will be able to customize in the end but we need to be able to adjust this just like the rainbow bridge in OoT. So here's my proposed settings to choose from based on what we currently have and how accessing The Moon currently works.

-Vanilla Requirements (4 remains + Oath)
-Oath to Order (so you just need Oath to access the moon)
-Remains (choose anywhere from 1-4)
-Open (perhaps a Tatl trigger to enter the moon?)
-Hearts (up to 20)
-Swamp and Ocean Skull Tokens (this is more relevant when Tokens can be shuffled)
-Stray Fairies
-Masks (up to 24)
-All Tokens (160)
-All Tokens and all Fairies (221)
-Variable Dungeon Rewards from both games (so any X number of dungeon rewards, i.e 2 stones and 2 remains if you set it to 4 dungeon rewards, or 3 meds and 4 remains if you set it to 7 dungeon rewards, etc). This would be up to 13 dungeon rewards.
-Stones (up to 3)
-Medallions (up to 6)
-All Masks + All Remains + Oath

Assume anything that doesn't list Oath is just an expected requirement BUT if Oath doesn't have to be required all the time then perhaps for settings that are naturally longer Oath shouldn't be a requirement (exception being the clearly 100% the seed option at the bottom lol).

But basically for the Remains, Hearts, Tokens, Stray Fairies, and Masks they would be configurable sliders just like the OoT variants. Remains would be 1-4, Hearts would be 4-20, Tokens would be 1-60, Stray Fairies would be 1-61 (the Clock Town Stray Fairy is the 61st fairy, I'm assuming it will be shuffled in the future with a Stray Fairy Shuffle setting). Masks would be 1-24.

**Comment by Nax** [comment]
Added everything except Open (needs a way to get to the moon without oath, maybe later?)
