### ISSUE TITLE
OOTxMM Settings: Song Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#71]
A setting that affects both games (and probably should be one of the first settings to offer), a simple drop-down for how songs are shuffled:

-Song Locations (songs are restricted to song locations, so in OoT for example when you go to Malon in the ranch you have a chance of picking up either an OoT song or a MM song or if you go to the monkey in Deku Palace in MM you have a chance of picking up either an OoT song or a MM song).

-Anywhere (songs are shuffled to be anywhere)

There _is_ a setting in OOTR to force songs at the end of dungeons (it uses the Well, Ice Cavern, and GTG to accomplish this) but it's not a very good setting so I'm not sure if it would end up being better here but probably not due to MM dungeons requiring songs to even access them in the first place. So I left it out for now.

**Comment by Nax** [comment]
Added!
