### ISSUE TITLE
OoT Settings: Gold Skull Token Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#74]
Basically what the title says. Shuffle Gold Skull Tokens but a drop-down list of options that consists of:

-Overworld Only (only skulls shuffled are the ones in the overworld e.g a Zora's River Skull will have an item)
-Dungeon Only (only skulls shuffled are the ones inside dungeons e.g a Fire Temple Skull will have an item)
-All Tokens
-CrossGame Tokens (Gold Skull Tokens are shuffled to the other games Skull Tokens and vice versa? Not sure how to do this but I liked the sound of it, also in the Swamp/Ocean Token setting issue I made)

**Comment by Nax** [comment]
👍 
Added, with the exception of `CrossGame`, as the MM skulls are not shuffled yet.
Closing this issue, as the cross games thing will be tracked by the MM issue.
