### ISSUE TITLE
OOTxMM Settings: Dungeon Reward Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#78]
Basically what it says in the title. A drop-down of this that allows the player to determine how Dungeon Rewards are shuffled consisting of the following options:

-End of Any Dungeon (current functionality)
-Any Dungeon (Medallions/Stones/Remains can be in any dungeon which would also include Ice Cavern, GTG, Well not sure if we are counting Ikana Castle, Beneath the Well, or Pirate's Fortress as dungeons?)
-Overworld Only (restricted to be shuffled only to overworld locations)
-Anywhere

This will also require the Pedestal in Temple of Time and the Sign in South Clock Town to state what **regions** the rewards are in. Basically, the current functionality for how dungeons are handled right now but instead any region. So, Pedestal would tell you "In... Kakariko Village", for example.

**Comment by Nax** [comment]
I assume "Any Dungeon" is still restricted to (at most) one per dungeon?
What about the "Sacred Realm" (behind DoT) reward?

**Comment by Revvenn** [comment]
> I assume "Any Dungeon" is still restricted to (at most) one per dungeon? What about the "Sacred Realm" (behind DoT) reward?

1. Yeah, one per dungeon if that's possible? When I was testing remains in any dungeon in MMR via plando there were seeds where Snowhead Temple had three(!) remains. It was funny but it definitely sucked the fun out of it.
2. Sacred Realm is a good point. The way 3D Rando handles that I think is by having a separate setting called "Link's Pocket" and you have the choice to do one of the following when you shuffle rewards besides the basic rando functionality:

-Dungeon Reward (so you guarantee start with a dungeon reward, for us this would somehow apply to either game?)
-Advancement (Link will receive a random advancement at the beginning of the playthrough)
-Anything (a completely random starting item)
-Nothing (Link will start with a very useful green rupee)

So if you want to you could just default to Dungeon Reward to keep it easy and not have a separate setting to customize.

**Comment by Nax** [comment]
Added the basic version of this
