### ISSUE TITLE
QoL: OoT and MM Current Gold/Swamp/Ocean Skull Count in Textbox

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#79]
In OOTR when you collect a Gold Skull token the textbox was changed to state how many tokens you've collected rather than saying you got one. Here is a screenshot of it, I can't find a PR for it in OOTR github sadly but hopefully you can add this in the near future.

![Screenshot (2)](https://user-images.githubusercontent.com/40970119/206080913-231a8a38-b73f-4be3-8b05-af63fa4d20c6.png)

Edit: I've been informed the way OOTR implemented this was editing an existing textbox that's used somewhere in the game that already increments Gold Skulltula count. I'm not sure where/what this is but it is apparently a thing, maybe Link's high score board in his house?

If the same could be applied to Ocean and Swamp skull textboxes that would be great.

**Comment by Nax** [comment]
Done
