### ISSUE TITLE
OoT Setting: Skip Child Zelda

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#80]
Basically like the title says. This might need to wait for Starting Items to be available, though, given you need the Chicken to talk to Zelda and since you have trade items shuffled and all... The way OOTR will handle this going forward is by making it so when you set Zelda's Letter to vanilla and you start with the Letter it triggers the Skip Child Zelda settings. If you want to see how this is done, the Trade Quest Shuffle PR has it: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1710 (it is not merged to main yet but this **is** how it will be when it is)

And what Skip Child Zelda does is the following:

-Gives you a starting item or song (the one you would have gotten for talking to Zelda)
-Sets the flags for talking to Zelda (so Saria's Song location becomes available)

**Comment by mracsys** [comment]
I would use caution assuming OOTR will use that method for Skip Child Zelda with full trade shuffle. As far as I know there hasn't been a detailed review by any of the maintainers. Everything there is still subject to change until merging.

**Comment by Nax** [comment]
Does it change the behavior of Talon too? Or do you still need to wake him up?

**Comment by Revvenn** [comment]
With Skip Child Zelda, it acts as if you talked to Zelda at the start of the seed so you get the items from her (or song + item) and thus Talon is already moved to LLR. Since you have Malon working separately from that you can keep her behavior the same? (Still need to talk to her at HC to get her to move to LLR). Saria, of course, becomes available since it acts like you talked to Zelda already.

**Comment by Nax** [comment]
Added
