### ISSUE TITLE
QoL: Update Scrub/Merchant Textboxes to Match Item Selling

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#84]
Basically what the title says. This would affect the following checks:

- [x] Tingle Maps (putting this here too for when they eventually get shuffled)
- [x] OOT Scrubs
- [x] MM Scrubs (Termina Field and Goron Village)
- [x] OOT Bean Salesman (also price needs to be updated) but if MM Bean Salesman gets shuffled eventually too his textbox will need updating (will cross that bridge when we get there).
- [x] Medigoron in both games

Hopefully not forgetting any... but there will be more in the future, this is just the current grouping.

**Comment by Nax** [comment]
Done
