### ISSUE TITLE
Bug: MM Town Guards Behavior is Incorrect

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#91]
Basically after first cycle the guards will continue to stop you from exiting Clock Town even if you have a sword, you have to talk to them to let you pass. Zoey shared the exact issue she fixed here so hopefully this helps: https://github.com/ZoeyZolotova/mm-rando/commit/6171f04bc4e9327dd1d9059f10745de6829eef4e

**Comment by Nax** [comment]
Fixed
