### ISSUE TITLE
Bug: MM Mikau has Incorrect Behavior after Great Bay Temple is Cleared (also softlock)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#92]
When you try to heal Mikau after clearing Great Bay Temple you will not trigger the cutscene for the reward so you basically cannot get the reward. If you try talking to him with this state, you will softlock.

Here is the exact issue Zoey fixed for MMR: https://github.com/ZoeyZolotova/mm-rando/blob/445adeaf3e2863a365ed10e1991848a4826cdefc/MMR.Randomizer/Resources/mods/fix-great-bay-clear-mikau

**Comment by Revvenn** [comment]
I never got around to testing if this was actually the case but I swear I saw someone try and they didn't get the reward. The softlock might not actually be a thing but the lack of getting a reward part might be.

**Comment by Nax** [comment]
Talking to him works fine, but the reward is not obtained indeed

**Comment by Nax** [comment]
Fixed.
Funny thing, this was completely unrelated to the similar MMR bug, I actually had a terrible bug in my code which was only triggering when GBT was cleared due to complex technical reasons.
