### ISSUE TITLE
QoL: OoTxMM Fast Block/Etc Pushing

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/core#97]
Already had this in the doc for MM speedups but felt it was a good idea to still throw this as its own, separate issue due to finding the PR for OOTR for this and knowing where MMR has its block pushing stuff.

OOTR PR: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/300
MMR: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/Pushblock.asm
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/Pushblock.Patch.asm (also includes the Great Bay Temple valves/faucets)

**Comment by Nax** [comment]
Implemented in 74477fa449a2cd17f5f889cce70dfe8fd382fd51
